export const mindscapeManifest: Record<string, string> = {
  "agent_alice": "/mindscapes/agent_alice.png",
  "agent_anby": "/mindscapes/agent_anby.png",
  "agent_anton": "/mindscapes/agent_anton.png",
  "agent_astra": "/mindscapes/agent_astra.png",
  "agent_banyue": "/mindscapes/agent_banyue.png",
  "agent_ben": "/mindscapes/agent_ben.png",
  "agent_billy": "/mindscapes/agent_billy.png",
  "agent_burnice": "/mindscapes/agent_burnice.png",
  "agent_caesar": "/mindscapes/agent_caesar.png",
  "agent_corin": "/mindscapes/agent_corin.png",
  "agent_dialyn": "/mindscapes/agent_dialyn.png",
  "agent_ellen": "/mindscapes/agent_ellen.png",
  "agent_evelyn": "/mindscapes/agent_evelyn.png",
  "agent_grace": "/mindscapes/agent_grace.png",
  "agent_harumasa": "/mindscapes/agent_harumasa.png",
  "agent_hugo": "/mindscapes/agent_hugo.png",
  "agent_jane": "/mindscapes/agent_jane.png",
  "agent_ju_fufu": "/mindscapes/agent_ju_fufu.png",
  "agent_koleda": "/mindscapes/agent_koleda.png",
  "agent_lighter": "/mindscapes/agent_lighter.png",
  "agent_lucia": "/mindscapes/agent_lucia.png",
  "agent_lucy": "/mindscapes/agent_lucy.png",
  "agent_lycaon": "/mindscapes/agent_lycaon.png",
  "agent_manato": "/mindscapes/agent_manato.png",
  "agent_miyabi": "/mindscapes/agent_miyabi.png",
  "agent_nekomata": "/mindscapes/agent_nekomata.png",
  "agent_nicole": "/mindscapes/agent_nicole.png",
  "agent_orphie_magus": "/mindscapes/agent_orphie_magus.png",
  "agent_piper": "/mindscapes/agent_piper.png",
  "agent_pulchra": "/mindscapes/agent_pulchra.png",
  "agent_qingyi": "/mindscapes/agent_qingyi.png",
  "agent_rina": "/mindscapes/agent_rina.png",
  "agent_seed": "/mindscapes/agent_seed.png",
  "agent_seth": "/mindscapes/agent_seth.png",
  "agent_soldier_0_anby": "/mindscapes/agent_soldier_0_anby.png",
  "agent_soldier_11": "/mindscapes/agent_soldier_11.png",
  "agent_soukaku": "/mindscapes/agent_soukaku.png",
  "agent_trigger": "/mindscapes/agent_trigger.png",
  "agent_vivian": "/mindscapes/agent_vivian.png",
  "agent_yanagi": "/mindscapes/agent_yanagi.png",
  "agent_ye_shunguang": "/mindscapes/agent_ye_shunguang.png",
  "agent_yidhari": "/mindscapes/agent_yidhari.png",
  "agent_yinhu": "/mindscapes/agent_yinhu.png",
  "agent_yixuan": "/mindscapes/agent_yixuan.png",
  "agent_yuzuha": "/mindscapes/agent_yuzuha.png",
  "agent_zhao": "/mindscapes/agent_zhao.png",
  "agent_zhu_yuan": "/mindscapes/agent_zhu_yuan.png",
};

export function getLocalMindscapePath(agentId: string): string | null {
  return mindscapeManifest[agentId] ?? null;
}
